services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432' # Nuevo puerto para evitar conflictos
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: costosdb
    volumes:
      - costos-data:/var/lib/postgresql/data
volumes:
  costos-data:
